apiVersion: v1
kind: Pod
metadata:
  name: fastchat-controller
spec:
  hostNetwork: true
  containers:
    - name: controller
      image: '192.168.62.116:5000/fastchat:k8s'
      command:
        - 'python'
        - '-m'
        - 'fastchat.serve.controller'
