apiVersion: v1
kind: Pod
metadata:
  name: fastchat-webserver
spec:
  hostNetwork: true
  containers:
    - name: webserver
      image: '192.168.62.116:5000/fastchat:k8s'
      command:
        - 'python'
        - '-m'
        - 'fastchat.serve.gradio_web_server'
